In [3]:
import numpy as np
r1 = np.array([3.1,2,4,9])
r2 = np.array([8,-6,-8,-6])
r3 = np.array([-1,2,3,4])
r2 = r2 + (-8/3.1)*r1
r3 = r3 + (1/3.1)*r1
r3 = r3 + (2.64516129/11.16129032)*r2
print(r1)
print(r2)
print(r3)


[3.1 2.  4.  9. ]
[  0.         -11.16129032 -18.32258065 -29.22580645]
[ 0.00000000e+00 -2.89016810e-10 -5.20231219e-02 -2.31213880e-02]


In [51]:
x3 = -2.31213880e-02/-5.20231219e-02
print(x3)

0.44444445384197523


In [52]:
x2 = (-29.22580645 + 18.32258065 * 0.44444445384197523 )/-11.16129032
print(x2)

1.8888888735612788


In [53]:
x1 = (9 - 4*x3 -2*x2)/3.1
print(x1)

1.1111111088740457


In [7]:
r3 = np.array([1,-2,4,1])
r1 = np.array([8,-3,2,-3])
r2 = np.array([-1,10,2,5])
r2 = r2 + (-r2[0]/r1[0])*r1
r2 = np.around(r2,decimals=3)
print(r1,'\n',r2,'\n',r3,'\n')
r3 = r3 + (-r3[0]/r1[0])*r1
r3 = np.around(r3,decimals=3)
print(r1,'\n',r2,'\n',r3,'\n')
#r3,r2 = r2,r3
r3 = r3 + (-r3[1]/r2[1])*r2
r3=np.around(r3,decimals=3)
print(r1,'\n',r2,'\n',r3,'\n')

print(r1,'\n',r2,'\n',r3,'\n')

[ 8 -3  2 -3] 
 [0.    9.625 2.25  4.625] 
 [ 1 -2  4  1] 

[ 8 -3  2 -3] 
 [0.    9.625 2.25  4.625] 
 [ 0.    -1.625  3.75   1.375] 

[ 8 -3  2 -3] 
 [0.    9.625 2.25  4.625] 
 [0.    0.    4.13  2.156] 

[ 8 -3  2 -3] 
 [0.    9.625 2.25  4.625] 
 [0.    0.    4.13  2.156] 



In [55]:
x3 = r3[3]/r3[2]
print(x3)
x2 = (r2[3] - r2[2]*x3)/r2[1]
x1 = (r1[3] - r1[2]*x3 - r1[1]*x2)/r1[0]
print(x2,'\n',x1)

1.5660207669037691
0.07543253900869801 
 -0.11321798959768048


In [56]:
8*(-0.113) -3 * 0.057 + 2*1.566

2.0570000000000004

In [57]:
4.25 -2.25*1.5660377363972946

0.7264150931060871

In [43]:
2 - 2*1.5660377363972946

-1.1320754727945892

In [44]:
0.7264150931060871/9.625

0.075471697985048

In [45]:
0.075471697985048*3 + (-1.1320754727945892)

-0.9056603788394452

In [46]:
8 * x1 -3 *x2

-1.1320415338075378

In [47]:
9.625*x2

0.7260381879587183

In [68]:
rr1 = np.array([8,-3,2,2])
rr1 = rr1 * 1/rr1[0]
rr2 = np.array([0,9.625,2.25,4.25])
rr2 = rr2 * (1/rr2[1])
rr3 = np.array([0,0,4.12987013,6.46753247])
rr3 = rr3*(1/rr3[2])

In [70]:
rr2 = rr2 - (rr2[2]*rr3)
rr1 = rr1 - (rr1[2]*rr3)
rr1 = rr1 - rr1[1]*rr2
print(rr1,'\n',rr2,'\n',rr3)

[ 1.          0.          0.         -0.11320755] 
 [0.        1.        0.        0.0754717] 
 [0.         0.         1.         1.56603774]


In [89]:
#27
mat = np.array([[4.13,-2.20,0.95,3.02],[6.14,4.45,-1.45,-4.02],[1.03,1.86,0.44,5.22]])
for i in range(3):
    mat[i] = np.around(mat[i]/max(mat[i]),decimals=3)
    print(mat[i])
for i in range(2,0,-1):
    if(mat[i][0]>mat[i-1][0]):
        mat[i],mat[i-1] = mat[i-1],mat[i]
mat[1]=np.around(mat[1]-mat[1][0]/mat[0][0]*mat[0],decimals=3)
mat[2]=np.around(mat[2]-mat[2][0]/mat[0][0]*mat[0],decimals=3)
if(mat[1][1]<mat[2][1]):
    mat[1][1],mat[2][1] = mat[2][1],mat[1][1]
print(mat)
mat[2]=np.around(mat[2]-mat[2][1]/mat[1][1]*mat[1],decimals=3)
print(mat)
for i in range(3):
    mat[i] = np.around(mat[i]/mat[i][i],decimals=3)
print(mat)
mat[1] = np.around(mat[1] - (mat[1][2]*mat[2]),decimals=3)
mat[0] = np.around(mat[0] - (mat[0][2]*mat[2]),decimals=3)
mat[0] = np.around(mat[0] - (mat[0][1]*mat[1]),decimals=3)
print(mat)
rr1 = rr1 - (rr1[2]*rr3)
rr1 = rr1 - rr1[1]*rr2

[ 1.    -0.533  0.23   0.731]
[ 1.     0.725 -0.236 -0.655]
[0.197 0.356 0.084 1.   ]
[[ 1.    -0.533  0.23   0.731]
 [ 0.     1.258 -0.466 -1.386]
 [ 0.     0.461  0.039  0.856]]
[[ 1.    -0.533  0.23   0.731]
 [ 0.     1.258 -0.466 -1.386]
 [ 0.     0.     0.21   1.364]]
[[ 1.    -0.533  0.23   0.731]
 [ 0.     1.    -0.37  -1.102]
 [ 0.     0.     1.     6.495]]
[[ 1.     0.     0.    -0.07 ]
 [ 0.     1.     0.     1.301]
 [ 0.     0.     1.     6.495]]


In [8]:
U = np.array([[8,-3,2],[0,9.625,2.25],[0,0,4.13]])
print(np.linalg.inv(U).dot(np.array([[-3],[4.625],[2.152]])))

[[-0.37074935]
 [ 0.35871199]
 [ 0.52106538]]


In [15]:
import scipy
import scipy.linalg 
P,L,U = scipy.linalg.lu(np.array([[1,-2,4],[8,-3,2],[-1,10,2]]))
print(L,'\n',U)

[[ 1.          0.          0.        ]
 [-0.125       1.          0.        ]
 [ 0.125      -0.16883117  1.        ]] 
 [[ 8.         -3.          2.        ]
 [ 0.          9.625       2.25      ]
 [ 0.          0.          4.12987013]]


In [18]:
np.linalg.inv(L).dot(np.array([[-3],[7],[-2]]))

array([[-3.        ],
       [ 6.625     ],
       [-0.50649351]])

In [20]:
x = np.linalg.inv(U).dot(np.array([[-3],[7],[-2]]))
print(x)

[[ 0.06124929]
 [ 0.84048027]
 [-0.48427673]]


In [24]:
mat2 = np.array([[4,-2,3,-5],[3,3,5,-8],[-6,-1,4,3],[-4,2,-3,5.1]])
print(np.linalg.det(mat2))

19.699999999999925


In [81]:
#第56題
aug = np.array([[3,-1,2,1,0,0],[1,1,3,0,1,0],[-3,0,5,0,0,1]])
print(aug)
#print("標準答案\n",np.around(np.linalg.inv(np.array([[3,-1,2],[1,1,3],[-3,0,5]])),decimals=7))
print(np.around(aug[1] + (-aug[1][0]/aug[0][0])*aug[0],decimals = 7))
aug[1] = aug[1] + np.around((-aug[1][0]/aug[0][0])*aug[0],decimals = 7)
print(aug)
aug[2] = aug[2] + np.around((-aug[2][0]/aug[0][0])*aug[0],decimals=7)
print(aug)
aug[2] = aug[2] + np.around((-aug[2][1]/aug[1][1])*aug[1],decimals=7)
print(aug)
for i in range(0,3):
    aug[i] = np.around(aug[i]/aug[i][i],decimals=7)
#aug[2] = aug[2] + (-aug[2]/aug[0])*aug[0]
aug[1] = np.around(aug[1] + (-aug[1][2])*aug[2],decimals=7)
aug[0] = np.around(aug[0] + (-aug[0][2])*aug[2],decimals=7)
aug[0] = np.around(aug[0] + (-aug[0][1])*aug[1],decimals=7)
print(aug)

[[ 3 -1  2  1  0  0]
 [ 1  1  3  0  1  0]
 [-3  0  5  0  0  1]]
[ 0.         1.3333333  2.3333333 -0.3333333  1.         0.       ]
[[ 3 -1  2  1  0  0]
 [ 0  1  2  0  1  0]
 [-3  0  5  0  0  1]]
[[ 3 -1  2  1  0  0]
 [ 0  1  2  0  1  0]
 [ 0 -1  7  1  0  1]]
[[ 3 -1  2  1  0  0]
 [ 0  1  2  0  1  0]
 [ 0  0  9  1  1  1]]
[[1 0 0 0 0 0]
 [0 1 0 0 1 0]
 [0 0 1 0 0 0]]


In [10]:
##78題 jacobi
m3 = np.array([[7,-3,4,6],[2,5,3,-5],[-3,2,6,2]])
A = np.array([[7,-3,4],[2,5,3],[-3,2,6]])
b = np.array([[6],[-5],[2]])
x = np.linalg.inv(A).dot(b)
print(x)
x1 = 0
x2 = 0
x3 = 0
it = 0
print("it  x1   x2  x3")
while(abs(x1-x[0][0])>0.00001):
    it += 1 
    print(it,x1,x2,x3)
    t_x1 = (6 +3*x2 -4*x3)/7 
    t_x2 = (-5 -2*x1 -3*x3)/5
    t_x3 = (2+3*x1-2*x2)/6
    x1 = t_x1
    x2 = t_x2
    x3 = t_x3

[[-0.14332248]
 [-1.37459283]
 [ 0.71986971]]
it  x1   x2  x3
1 0 0 0
2 0.8571428571428571 -1.0 0.3333333333333333
3 0.2380952380952381 -1.542857142857143 1.0952380952380951
4 -0.42993197278911566 -1.7523809523809526 0.9666666666666668
5 -0.44625850340136075 -1.4080272108843537 0.7024943310657598
6 -0.14772270813087138 -1.2429931972789114 0.5795464852607709
7 -0.00673793326854539 -1.288638807904114 0.6738030450275349
8 -0.08016122911749735 -1.4015866537091028 0.759510636000432
9 -0.1775432150184338 -1.4236418899532601 0.7604482700109522
10 -0.18753124998622697 -1.3852516759991977 0.7191090224752031
11 -0.14745587398548649 -1.3564529134906311 0.7013182670066191
12 -0.12494740121405279 -1.3618086106097769 0.7117563675041337
13 -0.13320732883512365 -1.3770748600168592 0.7247958362628992
14 -0.14720113215745353 -1.38159457022369 0.7257546222547245
15 -0.14968602852713828 -1.3765723204898535 0.7202642906625032
16 -0.14439630344565327 -1.3722841629866465 0.7173477592330487
17 -0.140891932270

In [11]:
##79題 Gauss-Seidel

print(x)
x1 = 0
x2 = 0
x3 = 0
it = 0
print("it  x1   x2  x3")
while(abs(x1-x[0][0])>0.00001):
    it += 1 
    print(it,x1,x2,x3)
    x1 = (6 +3*x2 -4*x3)/7 
    x2 = (-5 -2*x1 -3*x3)/5
    x3 = (2+3*x1-2*x2)/6
    

[[-0.14332248]
 [-1.37459283]
 [ 0.71986971]]
it  x1   x2  x3
1 0 0 0
2 0.8571428571428571 -1.342857142857143 1.2095238095238094
3 -0.40952380952380946 -1.561904761904762 0.6492063492063492
4 -0.1832199546485261 -1.316235827664399 0.6804686318972033
5 -0.09579743008314434 -1.3699622071050643 0.7420886873267826
6 -0.1540344815174747 -1.3836394197890798 0.7175292325042891
7 -0.14586216991205658 -1.372172671537751 0.7177931388898887
8 -0.14109865288182968 -1.3742364221812013 0.7208628142861523
9 -0.14373721766974468 -1.3750228015037935 0.7198056583330589
10 -0.14347014826337373 -1.3744953356944858 0.7197633710998085
11 -0.14321992735467015 -1.374570051718017 0.7199133868953372
12 -0.1433376718193429 -1.374612963409465 0.7198688185601503


In [75]:
#66,68
mat = np.array([[6.03,1.99,3.01,1],[4.16,-1.23,1.27,1],[-4.81,9.34,0.987,1]])
A = np.array([[6.03,1.99,3.01],[4.16,-1.23,1.27],[-4.81,9.34,0.987]])
print(A)
maxx = 0
for i in range(3):
    tmp = 0
    for j in range(3):
        tmp+=A[j][i]
    if(abs(tmp)>maxx):
        maxx = tmp
    print(tmp,end=' ')
print('\n')
print("norm of A is",maxx)
print('\n')
A_int = np.linalg.inv(A)
print(A_int)
maxx = 0
for i in range(3):
    tmp = 0
    for j in range(3):
        tmp+=A_int[j][i]
    if(abs(tmp)>maxx):
        maxx = tmp
    print(tmp,end=' ')
print('\n')
print("norm of A^-1 is",maxx)
print('\n')
print(10.1*0.185)
d = 4
mat[1]=np.around(mat[1]-mat[1][0]/mat[0][0]*mat[0],decimals=d)
mat[2]=np.around(mat[2]-mat[2][0]/mat[0][0]*mat[0],decimals=d)

print(mat)
mat[2]=np.around(mat[2]-mat[2][1]/mat[1][1]*mat[1],decimals=d)
print(mat)
for i in range(3):
    mat[i] = np.around(mat[i]/mat[i][i],decimals=d)
print(mat)
mat[1] = np.around(mat[1] - (mat[1][2]*mat[2]),decimals=d)
mat[0] = np.around(mat[0] - (mat[0][2]*mat[2]),decimals=d)
mat[0] = np.around(mat[0] - (mat[0][1]*mat[1]),decimals=d)
print(mat)

[[ 6.03   1.99   3.01 ]
 [ 4.16  -1.23   1.27 ]
 [-4.81   9.34   0.987]]
5.380000000000002 10.1 5.2669999999999995 

norm of A is 10.1


[[  428.05405423  -856.03117808  -203.93425235]
 [  334.38918915  -668.79376438  -159.21314953]
 [-1078.27256924  2157.06564616   513.80654792]]
-315.82932586039715 632.2407036995417 150.6591460398958 

norm of A^-1 is 632.2407036995417


1.8684999999999998
[[ 6.03    1.99    3.01    1.    ]
 [ 0.     -2.6029 -0.8066  0.3101]
 [ 0.     10.9274  3.388   1.7977]]
[[ 6.0300e+00  1.9900e+00  3.0100e+00  1.0000e+00]
 [ 0.0000e+00 -2.6029e+00 -8.0660e-01  3.1010e-01]
 [ 0.0000e+00  0.0000e+00  1.8000e-03  3.0996e+00]]
[[ 1.000e+00  3.300e-01  4.992e-01  1.658e-01]
 [-0.000e+00  1.000e+00  3.099e-01 -1.191e-01]
 [ 0.000e+00  0.000e+00  1.000e+00  1.722e+03]]
[[ 1.000000e+00  0.000000e+00  0.000000e+00 -6.833135e+02]
 [-0.000000e+00  1.000000e+00  0.000000e+00 -5.337669e+02]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  1.722000e+03]]


In [64]:
print(0.00159259954 - 0.00172)

-0.00012740046000000007


In [80]:
#73
print(A)
b=np.array([[1],[1],[1]])
x=np.array([[-0.0683],[-0.0533],[0.0017]])
print (A.dot(x))

while(abs(A.dot(x)[0][0]-1)>0.00001):
    print(A.dot(x)[0][0]-1)
    x = np.linalg.inv(A).dot(b)
    r = b- A.dot(x)
    print("r",r)
    e = np.linalg.inv(A).dot(r)
    print("e",e)
    x = x + e
    print(x)
print(A.dot(x))

[[ 6.03   1.99   3.01 ]
 [ 4.16  -1.23   1.27 ]
 [-4.81   9.34   0.987]]
[[-0.512799 ]
 [-0.21641  ]
 [-0.1676211]]
-1.512799
r [[1.81898940e-12]
 [1.36424205e-12]
 [2.27373675e-13]]
e [[-4.35577223e-10]
 [-3.40347065e-10]
 [ 1.09821937e-09]]
[[-631.9113762 ]
 [-493.61772476]
 [1592.59962484]]
[[1.]
 [1.]
 [1.]]
